### ISSUE TITLE
Fails to detect shapes in divided polygon

### ISSUE THREAD

**Issue by mootari** [neelts/figma-split-vectors#1]
Thanks for this plugin! Unfortunately it fails to detect the individual shapes in [this vector network](https://www.figma.com/file/ZWKjECNx52zDQtiwHFLvzt/Split-Vectors-Test-Case):

![image](https://user-images.githubusercontent.com/322014/80600002-1395cd00-8a2c-11ea-8d40-1c61a1fc87c4.png)

Selecting *Plugins > Split Vectors > Shapes* fails with the message "Polygon has only one shape".

**Comment by mootari** [comment]
It looks like you should be able to access all regions and their vertices via the `vectorNetwork` property:

![image](https://user-images.githubusercontent.com/322014/80601287-e8ac7880-8a2d-11ea-8d79-2f879c24250f.png)

**Comment by neelts** [comment]
Hi! It's a single shape, try Fills

**Comment by mootari** [comment]
Huh, could have sworn that Fills resulted in a single shape last time I tried. Anyway, it works. Thanks, and sorry for the noise!
