### ISSUE TITLE
Can't Split because vector has one fill region or Shape

### ISSUE THREAD

**Issue by Bilalharoon** [neelts/figma-split-vectors#2]
Whenever I try to split a vector by fill region it says that their is only one fill region even though the paint bucket tool shows multiple regions.

**Comment by neelts** [comment]
[Split-Vectors](https://www.figma.com/community/plugin/769868828362075393/Split-Vectors)
> Known issues:
> 
> Due to API limitations, it is currently impossible to get all possible fill areas automatically after filling a Vector, so you need to manually add fills with Paint Bucket (B) before splitting.
